services:
  mongodb:
    image: mongo:7
    container_name: pdf-forms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pdf-forms

volumes:
  mongo-data:
